### ISSUE TITLE
Secrets

### ISSUE THREAD

**Issue by gwpeacock** [ThisIsQasim/WebGPIO#14]
Getting this error when I try to run:
ImportError: No module named 'secrets'

Not sure what to do next.

**Comment by ThisIsQasim** [comment]
Which version of python are you running it with? I recommend you try this  `python3.6 backend.py`

**Comment by ThisIsQasim** [comment]
I have pushed a commit that removes the dependency of `secrets` module available only in python3.6. Pull the code and try again

**Comment by gwpeacock** [comment]
Running python 3.5 on a raspberry pi. I'll see if I can figure out how to
upgrade.

Thanks

**Comment by gwpeacock** [comment]
Got it. Thanks for your help.

**Comment by ThisIsQasim** [comment]
Happy to help. Closing issue
