### ISSUE TITLE
rename config file

### ISSUE THREAD

**Issue by Stephan-e** [ThisIsQasim/WebGPIO#15]
Hey

You renamed the accessories to appliances, please update the exampleconfig.yaml because it gives an error on install. 

Thanks

**Comment by ThisIsQasim** [comment]
Hi

I thought I already updated that. Can you share the error you are getting?

**Comment by Stephan-e** [comment]
ahhh yeah sorry, I had the previous version of your code with a newer config and then it bugged out.
I did manage to sort it out. 

I have a question, is it possible to view sensor data in your front end? 
I can do that via the script section of the config, but there doesn't seem like an easy way to display data coming from a sensor plugged into the pi. 

Also the use case is very specific to home automation, I would like to use this for monitoring the status of a plant.

**Comment by ThisIsQasim** [comment]
Glad to know you sorted it out.

As for your question, if your sensor can be read from python then yes we can add another accessory type.
