### ISSUE TITLE
Pulse gpio

### ISSUE THREAD

**Issue by yuguar** [ThisIsQasim/WebGPIO#8]
Hi there ,
Is there any possibility to change code to be able to pulse gpio for set amount of time ?
As in after web click to change gpio state (turn on relay) and after set period of time change back to previous state (turn off relay) .
This is wery useful for some applications as in remotes (garages) or some motor actuated valves etc. 
Thanks for reading and keep up the good work !

**Comment by ThisIsQasim** [comment]
It is certainly possible. I’ll see if I can spare some time over the weekend, shouldn’t take long. Any suggestions as to how to go about the UI?

On 12-Apr-2018, at 1:00 AM, yuguar <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there ,
Is there any possibility to change code to be able to pulse gpio for set amount of time ?
As in after web click to change gpio state (turn on relay) and after set period of time change back to previous state (turn off relay) .
This is wery useful for some applications as in remotes (garages) or some motor actuated valves etc.
Thanks for reading and keep up the good work !

**Comment by yuguar** [comment]
Well it could only be done in script (to set duration in seconds or miliseconds...as done for pin numbering and "section" names) to keep it simple for usage with non variable "things" ..relays,remotes,motor actuators etc..
Luxury variant would be clickable (editable) box in GUI for user to input duration ..useable for lights , sprinklers , hot water tanks etc ..would it be in seconds minutes or how ever coder sees fit ;)  .

**Comment by ThisIsQasim** [comment]
All configs should now be defined in `config.yml` file. You can now define a `duration` key for a pin so it will turn on for the given certain duration and then turn off.

**Comment by kevin9r** [comment]
If i try to put the duration to another pin i receive: Config file not found. Please provide a valid config.yml file. See exampleconfig.yml for reference. My config.yml:

`Last login: Wed Jun 13 12:43:14 on ttys000
Jedynaks-MacBook-Pro:~ jedyn$ ssh pi@192.168.0.141
pi@192.168.0.141's password: 
Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Jun 13 10:45:24 2018
pi@raspberrypi:~ $ ls
Desktop    Music         Public                            Templates
Documents  node_modules  python_games                      Videos
Downloads  oldconffiles  Raspberry-Pi-Simple-Web-GPIO-GUI  WebGPIO
Keysystem  Pictures      startKey.sh
pi@raspberrypi:~ $ cd WebGPIO/
pi@raspberrypi:~/WebGPIO $ ls
backend.py  exampleconfig.yml  LICENSE    screenshots  static
config.yml  lib                README.md  scripts      templates
pi@raspberrypi:~/WebGPIO $ sudo nano config.yml 
pi@raspberrypi:~/WebGPIO $ git clone https://github.com/ThisIsQasim/WebGPIO
Klone nach 'WebGPIO' ...
remote: Counting objects: 524, done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 524 (delta 59), reused 78 (delta 32), pack-reused 414
Empfange Objekte: 100% (524/524), 674.84 KiB | 581.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (246/246), Fertig.
pi@raspberrypi:~/WebGPIO $ cd ..
pi@raspberrypi:~ $ rm -rf WebGPIO/
pi@raspberrypi:~ $ ls
Desktop    Music         Public                            Templates
Documents  node_modules  python_games                      Videos
Downloads  oldconffiles  Raspberry-Pi-Simple-Web-GPIO-GUI
Keysystem  Pictures      startKey.sh
pi@raspberrypi:~ $ git clone https://github.com/ThisIsQasim/WebGPIOc
Klone nach 'WebGPIOc' ...
Username for 'https://github.com': kevin9r
Password for 'https://kevin9r@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/ThisIsQasim/WebGPIOc/'
pi@raspberrypi:~ $ git clone https://github.com/ThisIsQasim/WebGPIOc
Klone nach 'WebGPIOc' ...
Username for 'https://github.com': kevin9r
Password for 'https://kevin9r@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/ThisIsQasim/WebGPIOc/' not found
pi@raspberrypi:~ $ git clone git@github.com:ThisIsQasim/WebGPIO.git
Klone nach 'WebGPIO' ...
Permission denied (publickey).
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
pi@raspberrypi:~ $ git@github.com:ThisIsQasim/WebGPIO.git
-bash: git@github.com:ThisIsQasim/WebGPIO.git: Datei oder Verzeichnis nicht gefunden
pi@raspberrypi:~ $ git clone https://github.com/ThisIsQasim/WebGPIO
Klone nach 'WebGPIO' ...
remote: Counting objects: 528, done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 528 (delta 62), reused 82 (delta 35), pack-reused 414
Empfange Objekte: 100% (528/528), 675.24 KiB | 578.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (249/249), Fertig.
pi@raspberrypi:~ $ cd WebGPIO
pi@raspberrypi:~/WebGPIO $ cp exampleconfig.yml config.yml
pi@raspberrypi:~/WebGPIO $ python3 backend.py 
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
[2018-06-13 12:01:56,581] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "backend.py", line 29, in main
    'rooms' : updateStates(rooms),
  File "backend.py", line 14, in updateStates
    rooms[i]['Accesories'][j]['State'] = current_accesory.getState()
  File "/home/pi/WebGPIO/lib/accesory.py", line 29, in getState
    if GPIO.input(self.pin) is settings['ActiveValue']:
RuntimeError: You must setup() the GPIO channel first
192.168.0.140 - - [13/Jun/2018 12:01:56] "GET / HTTP/1.1" 500 -
[2018-06-13 12:01:58,993] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "backend.py", line 29, in main
    'rooms' : updateStates(rooms),
  File "backend.py", line 14, in updateStates
    rooms[i]['Accesories'][j]['State'] = current_accesory.getState()
  File "/home/pi/WebGPIO/lib/accesory.py", line 29, in getState
    if GPIO.input(self.pin) is settings['ActiveValue']:
RuntimeError: You must setup() the GPIO channel first
192.168.0.140 - - [13/Jun/2018 12:01:58] "GET / HTTP/1.1" 500 -
^Cpi@raspberrypi:~/WebGPIO $ python3 backend.py 
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
[2018-06-13 12:02:13,010] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "backend.py", line 29, in main
    'rooms' : updateStates(rooms),
  File "backend.py", line 14, in updateStates
    rooms[i]['Accesories'][j]['State'] = current_accesory.getState()
  File "/home/pi/WebGPIO/lib/accesory.py", line 29, in getState
    if GPIO.input(self.pin) is settings['ActiveValue']:
RuntimeError: You must setup() the GPIO channel first
192.168.0.140 - - [13/Jun/2018 12:02:13] "GET / HTTP/1.1" 500 -
^Cpi@raspberrypi:~/WebGPIO $ cd ..
pi@raspberrypi:~ $ rm -rf WebGPIO/
pi@raspberrypi:~ $ git clone https://github.com/ThisIsQasim/WebGPIO
Klone nach 'WebGPIO' ...
remote: Counting objects: 532, done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 532 (delta 66), reused 84 (delta 36), pack-reused 413
Empfange Objekte: 100% (532/532), 675.57 KiB | 447.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (253/253), Fertig.
pi@raspberrypi:~ $ cd WebGPIO
pi@raspberrypi:~/WebGPIO $ cp exampleconfig.yml config.yml
pi@raspberrypi:~/WebGPIO $ python3 backend.py     
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
192.168.0.140 - - [13/Jun/2018 12:24:33] "GET / HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:24:33] "GET /static/spinner.css HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:24:33] "GET /static/android-icon-192x192.png HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:24:33] "GET /static/favicon-32x32.png HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:24:33] "GET /static/favicon-96x96.png HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:24:33] "GET /static/favicon-16x16.png HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:24:35] "GET /button/0/2/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:24:38] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:24:43] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:24:48] "GET /grid/ HTTP/1.1" 200 -
Failed to start nginx.service: Unit nginx.service not found.
192.168.0.140 - - [13/Jun/2018 12:24:51] "GET /button/2/1/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:24:53] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:24:58] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:03] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:08] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:09] "GET /button/0/1/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:10] "GET /button/0/1/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:11] "GET /button/0/2/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:13] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:15] "GET /button/0/0/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:16] "GET /button/0/1/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:16] "GET /button/0/2/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:17] "GET /button/0/3/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:18] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:23] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:29] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:36] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:42] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:54] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:57] "GET /button/1/1/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:25:59] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:26:04] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:26:09] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:26:14] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:26:21] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:26:26] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:26:31] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:26:39] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:26:49] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:27:07] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:27:12] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:27:36] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:27:41] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:27:46] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:27:51] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:27:56] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:28:04] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:28:12] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:28:22] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:28:36] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:28:37] "GET /button/0/2/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:28:38] "GET /button/0/1/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:28:41] "GET /grid/ HTTP/1.1" 200 -
^Cpi@raspberrypi:~/WebGPIO $ ls
backend.py  exampleconfig.yml  LICENSE    screenshots  static
config.yml  lib                README.md  scripts      templates
pi@raspberrypi:~/WebGPIO $ cd lib/
pi@raspberrypi:~/WebGPIO/lib $ ls
accesory.py  cors.py  GPIOSetup.py  __pycache__  setup.py
pi@raspberrypi:~/WebGPIO/lib $ cd G
-bash: cd: G: Datei oder Verzeichnis nicht gefunden
pi@raspberrypi:~/WebGPIO/lib $ sudo nano GPIOSetup.py 
pi@raspberrypi:~/WebGPIO/lib $ ls
accesory.py  cors.py  GPIOSetup.py  __pycache__  setup.py
pi@raspberrypi:~/WebGPIO/lib $ ls
accesory.py  cors.py  GPIOSetup.py  __pycache__  setup.py
pi@raspberrypi:~/WebGPIO/lib $ cd ..
pi@raspberrypi:~/WebGPIO $ ls
backend.py  config.yml  exampleconfig.yml  lib  LICENSE  README.md  screenshots  scripts  static  templates
pi@raspberrypi:~/WebGPIO $ sudo nano config.yml 
pi@raspberrypi:~/WebGPIO $ sudo nano config.yml 
pi@raspberrypi:~/WebGPIO $ python3 backend.py     
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
192.168.0.140 - - [13/Jun/2018 12:48:32] "GET / HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:48:38] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:48:43] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:48:43] "GET /button/1/0/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:48:48] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:48:50] "GET /button/1/1/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:48:53] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:48:53] "GET /button/1/0/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:48:54] "GET /button/1/0/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:48:56] "GET /button/1/0/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:48:58] "GET /grid/ HTTP/1.1" 200 -
192.168.0.140 - - [13/Jun/2018 12:48:58] "GET /button/1/1/ HTTP/1.1" 200 -
^Cpi@raspberrypi:~/WebGPIO $ sudo nano config.yml 
pi@raspberrypi:~/WebGPIO $ python3 backend.py     
Config file not found. Please provide a valid config.yml file. See exampleconfig.yml for reference
pi@raspberrypi:~/WebGPIO $ python3 backend.py     
Config file not found. Please provide a valid config.yml file. See exampleconfig.yml for reference
pi@raspberrypi:~/WebGPIO $ ls
backend.py  config.yml  exampleconfig.yml  lib  LICENSE  README.md  screenshots  scripts  static  templates
pi@raspberrypi:~/WebGPIO $ sudo nano config.yml 
pi@raspberrypi:~/WebGPIO $ python3 backend.py     
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
192.168.0.140 - - [13/Jun/2018 12:50:07] "GET / HTTP/1.1" 200 -
^Cpi@raspberrypi:~/WebGPIO $ sudo nano config.yml 
pi@raspberrypi:~/WebGPIO $ python3 backend.py     
Config file not found. Please provide a valid config.yml file. See exampleconfig.yml for reference
pi@raspberrypi:~/WebGPIO $ sudo nano config.yml 
pi@raspberrypi:~/WebGPIO $ ls
backend.py  config.yml  exampleconfig.yml  lib  LICENSE  README.md  screenshots  scripts  static  templates
pi@raspberrypi:~/WebGPIO $ sudo nano exampleconfig.yml 
pi@raspberrypi:~/WebGPIO $ sudo nano config.yml 

  GNU nano 2.7.4                                Datei: config.yml                                            

      - Name: Internet
        Type: Script
        Status: ping -c 1 8.8.8.8 > /dev/null
        Timeout: 0.3
      - Name: Nginx
        Type: Script
        Status: sudo systemctl is-active --quiet nginx 2> /dev/null
        Action:
          On: sudo systemctl start nginx
          Off: sudo systemctl stop nginx


#Settings:
#  Host: 0.0.0.0
#  Port: 8000
#  Debug: True
#  SSL:
#    Enabled: False
#    Path: default
#    Certificate: WebGPIO.cer
#    Key: WebGPIO.key
#  Inverted: False
#  RefreshRate: 4

`

**Comment by ThisIsQasim** [comment]
It appears to be an indentation issue. The example config is using two spaces to for each level. Since `Duration` key should be defined at the fourth level you should make sure there are 8 spaces before it.

**Comment by kevin9r** [comment]
Hey, i don't understand what you mean? Can you explain it with a example? Thanks!

**Comment by ThisIsQasim** [comment]
Your config.yml file has a syntax error since you have put a tab before the `Duration:` key. Convert the tab to spaces and it will work. You can also verify your yml file by uploading it to [yamlint.com](http://www.yamllint.com/)
